apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    app: eureka-deployment
  ports:
    - nodePort: 30500
      protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort