apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      hostname: eureka-service
      containers:
        - name: eureka-service
          image: ielenagm/eurekaservice
          ports:
            - containerPort: 8761
          env:
            - name: spring.cloud.config.uri
              value: http://config-service:8081
            - name: spring.config.import
              value: optional:configserver:http://config-service:8081