apiVersion: v1
kind: Service
metadata:
  name: pago-service
  labels:
    app: pago-service
spec:
  selector:
    app: pago-deployment
  ports:
    protocol: TCP
    port: 8085
    targetPort: 8085
  type: LoadBalancer