apiVersion: apps/v1
kind: Deployment
metadata:
  name: pago-deployment
  labels:
    app: pago-deployment
spec:
  selector:
    matchLabels:
      app: pago-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pago-deployment
    spec:
      containers:
        - name: pago-deployment
          image: ielenagm/pagoservice
          ports:
            - containerPort: 8085
          env:
            - name: spring.cloud.config.uri
              value: http://config-service:8081
            - name: spring.config.import
              value: optional:configserver:http://config-service:8081
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-service:8761/eureka
            - name: EUREKA
              value: eureka-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-pago:5432/pago
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-db
                  key: name1
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: password