apiVersion: apps/v1
kind: Deployment
metadata:
  name: calidad-deployment
  labels:
    app: calidad-deployment
spec:
  selector:
    matchLabels:
      app: calidad-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: calidad-deployment
    spec:
      containers:
        - name: calidad-service
          image: ielenagm/calidadservice
          ports:
            - containerPort: 8083
          env:
            - name: spring.cloud.config.uri
              value: http://config-service:8081
            - name: spring.config.import
              value: optional:configserver:http://config-service:8081
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-service:8761/eureka
            - name: EUREKA
              value: eureka-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-calidad:5432/calidad
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-db
                  key: name2
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: password