apiVersion: v1
kind: Service
metadata:
  name: calidad-service
  labels:
    app: calidad-service
spec:
  selector:
    app: calidad-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer